version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: observer
    ports:
      - "3003:3003"
    networks:
      - faas
networks:
  faas:
    driver: bridge