version: "3.0"
services:
  oauth2:
    image: bitnami/oauth2-proxy
    container_name: auth2_proxy
    ports:
      - 4180:4180/tcp
    env_file:
      - .env 
  web:
    image: mendhak/http-https-echo
    container_name: http_web
    ports: 
    - 8080:8080
    - 8443:8443